import { QuizQuestion } from '../types';

export const quizQuestions: QuizQuestion[] = [
  {
    id: 0,
    question: "What is my go-to comfort food when I'm sad?",
    options: ['Ice cream', 'Pizza', 'Ramen noodles', 'Chocolate'],
    correctIndex: 2,
    category: 'about-me',
  },
  {
    id: 1,
    question: 'Which song do I always skip in our shared playlist?',
    options: ['The newest pop hit', 'Anything with a slow beat', 'Songs with sad lyrics', 'Anything before 2010'],
    correctIndex: 1,
    category: 'us',
  },
  {
    id: 2,
    question: "What's the first thing I do every morning?",
    options: ['Check my phone', 'Brush my teeth', 'Make coffee/tea', 'Scroll social media'],
    correctIndex: 0,
    category: 'about-me',
  },
  {
    id: 3,
    question: 'What movie can I quote entirely from memory?',
    options: ['The Notebook', 'Interstellar', 'Harry Potter series', '3 Idiots'],
    correctIndex: 3,
    category: 'about-me',
  },
  {
    id: 4,
    question: 'If I could only eat one cuisine for the rest of my life, what would it be?',
    options: ['Italian', 'Indian', 'Japanese', 'Mexican'],
    correctIndex: 1,
    category: 'about-me',
  },
  {
    id: 5,
    question: "What do I do when I can't fall asleep at night?",
    options: ['Scroll my phone', 'Listen to music', 'Read a book', 'Think about you'],
    correctIndex: 3,
    category: 'about-me',
  },
  {
    id: 6,
    question: "What's my biggest pet peeve?",
    options: ['Loud chewing', 'Being late', 'Interrupting mid-sentence', 'Leaving lights on'],
    correctIndex: 2,
    category: 'about-me',
  },
  {
    id: 7,
    question: 'How do I take my coffee/tea?',
    options: ['Black, no sugar', 'Lots of milk, little sugar', 'Sweet and creamy', 'I prefer neither'],
    correctIndex: 1,
    category: 'about-me',
  },
  {
    id: 8,
    question: 'What was the first thing you noticed about me?',
    options: ['My eyes', 'My smile', 'My laugh', 'The way I talk'],
    correctIndex: 2,
    category: 'us',
  },
  {
    id: 9,
    question: 'What is my love language?',
    options: ['Words of affirmation', 'Quality time', 'Acts of service', 'Physical touch'],
    correctIndex: 1,
    category: 'about-me',
  },
  {
    id: 10,
    question: "What's my most-used emoji when texting?",
    options: ['😭', '🥺', '😂', '❤️'],
    correctIndex: 1,
    category: 'about-me',
  },
  {
    id: 11,
    question: 'When I get really excited about something, I tend to:',
    options: ['Go quiet and process internally', 'Talk about it non-stop', 'Message everyone immediately', 'Write it down'],
    correctIndex: 1,
    category: 'about-me',
  },
  {
    id: 12,
    question: "What's my biggest irrational fear?",
    options: ['Heights', 'Open water', 'Something bad happening to someone I love', 'Failure'],
    correctIndex: 2,
    category: 'about-me',
  },
  {
    id: 13,
    question: 'What was the first gift I ever gave you?',
    options: ['A book', 'Something handmade', 'Food/snacks', 'A digital playlist'],
    correctIndex: 3,
    category: 'us',
  },
  {
    id: 14,
    question: 'What time of day do I feel most like myself?',
    options: ['Early morning', 'Mid-afternoon', 'Late at night', 'Twilight hours'],
    correctIndex: 2,
    category: 'about-me',
  },
  {
    id: 15,
    question: 'What subject was I best at in school?',
    options: ['Math/Sciences', 'Languages/Literature', 'Arts/Music', 'History/Social Studies'],
    correctIndex: 0,
    category: 'about-me',
  },
  {
    id: 16,
    question: 'When I have a bad day, what do I need most?',
    options: ['Advice and solutions', 'To be left alone briefly', 'A hug and someone to listen', 'Distraction and humor'],
    correctIndex: 2,
    category: 'about-me',
  },
  {
    id: 17,
    question: "What's my secret talent that very few people know about?",
    options: ['I can sing', 'I can draw/paint', 'I can cook really well', 'I have a great memory for details'],
    correctIndex: 3,
    category: 'about-me',
  },
  {
    id: 18,
    question: 'What does my ideal Sunday look like?',
    options: ['Adventure and exploration', 'Absolute couch potato mode', 'Brunch + light socializing', 'Working on a project'],
    correctIndex: 1,
    category: 'about-me',
  },
  {
    id: 19,
    question: "What's the one thing I always forget to do?",
    options: ['Reply to messages', 'Drink enough water', 'Charge my phone', 'Eat breakfast'],
    correctIndex: 1,
    category: 'about-me',
  },
  {
    id: 20,
    question: "What's the last thing I do before sleeping?",
    options: ['Set multiple alarms', 'Check tomorrow\'s weather', 'Reread our texts', 'Watch something'],
    correctIndex: 2,
    category: 'us',
  },
  {
    id: 21,
    question: "What do I genuinely think is my best physical feature?",
    options: ['My eyes', 'My hair', 'My hands', 'My smile'],
    correctIndex: 0,
    category: 'about-me',
  },
  {
    id: 22,
    question: 'Which of these best describes my texting style?',
    options: ['Long, detailed paragraphs', 'Short bursts of messages', 'Voice notes over texts', 'Extremely consistent responder'],
    correctIndex: 1,
    category: 'about-me',
  },
  {
    id: 23,
    question: "What's a skill I've been meaning to learn for years but haven't?",
    options: ['A new language', 'An instrument', 'Cooking something specific', 'A craft or art form'],
    correctIndex: 0,
    category: 'about-me',
  },
  {
    id: 24,
    question: "What's the moment I knew I was falling for you?",
    options: ['First conversation', 'When you made me laugh unexpectedly', 'When you showed you genuinely care', 'A specific late-night call'],
    correctIndex: 3,
    category: 'us',
  },
  {
    id: 25,
    question: 'How do I handle conflict or arguments?',
    options: ['I go silent and need time', 'I want to resolve it immediately', 'I overthink every word said', 'I become sarcastic unintentionally'],
    correctIndex: 2,
    category: 'about-me',
  },
  {
    id: 26,
    question: "What's my go-to playlist genre when working or studying?",
    options: ['Lo-fi / chill beats', 'Instrumental/classical', 'Pop/upbeat', 'Silence — I can\'t work with music'],
    correctIndex: 0,
    category: 'about-me',
  },
  {
    id: 27,
    question: "Which of these words best describes my personality?",
    options: ['Analytical', 'Intuitive', 'Empathetic', 'Ambitious'],
    correctIndex: 2,
    category: 'about-me',
  },
  {
    id: 28,
    question: "What's something I do that I don't realize is adorable?",
    options: ['Getting flustered over small things', 'Talking too fast when excited', 'Squinting when thinking hard', 'Apologizing for everything'],
    correctIndex: 1,
    category: 'us',
  },
  {
    id: 29,
    question: "If I won the lottery tomorrow, what's the first non-practical thing I'd do?",
    options: ['Book a trip around the world', 'Buy a ridiculous amount of books', 'Get us in the same city immediately', 'Buy every tech gadget I want'],
    correctIndex: 2,
    category: 'us',
  },
  {
    id: 30,
    question: 'What do I find most attractive in a person (beyond looks)?',
    options: ['Intelligence and wit', 'Kindness and warmth', 'Ambition and drive', 'A great sense of humor'],
    correctIndex: 1,
    category: 'about-me',
  },
  {
    id: 31,
    question: "What's my relationship with punctuality?",
    options: ['Always early — it\'s a principle', 'Exactly on time', 'A few minutes late usually', 'Time is more of a suggestion'],
    correctIndex: 2,
    category: 'about-me',
  },
  {
    id: 32,
    question: "What kind of movie am I most likely to cry at?",
    options: ['Sad romantic films', 'Animal stories / endings', 'Reunion scenes', 'I rarely cry at movies'],
    correctIndex: 2,
    category: 'about-me',
  },
  {
    id: 33,
    question: "What's my most-visited app (other than our chat)?",
    options: ['Instagram/social media', 'YouTube', 'Spotify/music', 'Reddit or news'],
    correctIndex: 2,
    category: 'about-me',
  },
  {
    id: 34,
    question: 'How do I react when someone gives me a genuine compliment?',
    options: ['Accept it graciously', 'Immediately deflect or minimize it', 'Return one right away', 'Get awkwardly quiet'],
    correctIndex: 1,
    category: 'about-me',
  },
  {
    id: 35,
    question: "What's a non-negotiable in my daily routine?",
    options: ['Morning shower', 'Evening walk', 'Tea or coffee ritual', 'Reading before bed'],
    correctIndex: 2,
    category: 'about-me',
  },
  {
    id: 36,
    question: "What's the most important value I hold?",
    options: ['Loyalty', 'Honesty', 'Family', 'Freedom'],
    correctIndex: 1,
    category: 'about-me',
  },
  {
    id: 37,
    question: "What's something I'm secretly proud of?",
    options: ['How far I\'ve come despite setbacks', 'A specific skill', 'My taste in music/art', 'How I treat people'],
    correctIndex: 0,
    category: 'about-me',
  },
  {
    id: 38,
    question: 'What do I miss most about us not being in the same place?',
    options: ['Simple physical proximity', 'Spontaneous moments', 'Shared meals', 'Falling asleep knowing you\'re nearby'],
    correctIndex: 3,
    category: 'us',
  },
  {
    id: 39,
    question: "What's the silliest thing we've argued about?",
    options: ['A movie opinion', 'Response time to a message', 'Food preferences', 'Pronunciation of a word'],
    correctIndex: 1,
    category: 'us',
  },
  {
    id: 40,
    question: "What's a word I overuse constantly?",
    options: ['"Basically"', '"Honestly"', '"Literally"', '"Actually"'],
    correctIndex: 1,
    category: 'about-me',
  },
  {
    id: 41,
    question: "What kind of drunk am I (hypothetically)?",
    options: ['Philosophical and deep', 'Giggly and silly', 'Emotional and honest', 'Energetic and social'],
    correctIndex: 2,
    category: 'fun',
  },
  {
    id: 42,
    question: "In a fantasy world, what would my superpower be?",
    options: ['Teleportation (to you, obviously)', 'Time manipulation', 'Reading minds', 'Healing people'],
    correctIndex: 0,
    category: 'fun',
  },
  {
    id: 43,
    question: "What's my spirit animal?",
    options: ['A wolf — loyal and intense', 'A cat — independent but loving', 'A dog — warm and devoted', 'An owl — observant and wise'],
    correctIndex: 2,
    category: 'fun',
  },
  {
    id: 44,
    question: 'If I could live in any fictional universe, where would I choose?',
    options: ['Harry Potter\'s wizarding world', 'The MCU', 'Studio Ghibli\'s world', 'A slice-of-life anime'],
    correctIndex: 2,
    category: 'fun',
  },
  {
    id: 45,
    question: "What's the strangest food combination I genuinely enjoy?",
    options: ['Sweet + salty together', 'Spicy + sweet', 'Weird snack dunked in something', 'I\'m a food purist'],
    correctIndex: 0,
    category: 'fun',
  },
  {
    id: 46,
    question: 'How would I describe our relationship in one genre?',
    options: ['Slow-burn romance novel', 'An indie coming-of-age film', 'An epic with quiet beautiful moments', 'A playlist that keeps getting better'],
    correctIndex: 2,
    category: 'us',
  },
  {
    id: 47,
    question: "What's my most chaotic trait?",
    options: ['Starting 10 things and finishing 3', 'Hyperfixating on something new every month', 'My sleep schedule', 'Saying "I\'ll reply in a sec" and taking hours'],
    correctIndex: 2,
    category: 'about-me',
  },
  {
    id: 48,
    question: "If our relationship had a theme song, what vibe would it be?",
    options: ['Soft acoustic and tender', 'Cinematic and sweeping', 'Indie / lo-fi and warm', 'Soul / R&B and deep'],
    correctIndex: 2,
    category: 'us',
  },
  {
    id: 49,
    question: "What's one thing I want us to do the very first day we're in the same place again?",
    options: ['Eat somewhere amazing together', 'Just stay in and exist quietly', 'Take a walk with no destination', 'Do something we\'ve planned for months'],
    correctIndex: 1,
    category: 'us',
  },
];
