import { ThisOrThatQuestion } from '../types';

export const thisOrThatQuestions: ThisOrThatQuestion[] = [
  { id: 0, optionA: 'Late night walks', emojiA: '🌙', optionB: 'Cozy movie night', emojiB: '🎬', category: 'lifestyle' },
  { id: 1, optionA: 'Mountains', emojiA: '⛰️', optionB: 'Beach', emojiB: '🏖️', category: 'travel' },
  { id: 2, optionA: 'Cook together', emojiA: '🍳', optionB: 'Order in', emojiB: '🍕', category: 'food' },
  { id: 3, optionA: 'Texting all day', emojiA: '💬', optionB: 'One long call at night', emojiB: '📞', category: 'romance' },
  { id: 4, optionA: 'Morning person', emojiA: '🌅', optionB: 'Night owl', emojiB: '🦉', category: 'lifestyle' },
  { id: 5, optionA: 'Spontaneous plans', emojiA: '✈️', optionB: 'Well-planned trips', emojiB: '🗺️', category: 'travel' },
  { id: 6, optionA: 'Coffee', emojiA: '☕', optionB: 'Tea', emojiB: '🍵', category: 'food' },
  { id: 7, optionA: 'Spend the day in bed', emojiA: '🛏️', optionB: 'Explore a new place', emojiB: '🗺️', category: 'lifestyle' },
  { id: 8, optionA: 'Surprise dates', emojiA: '🎁', optionB: 'Planned romantic evenings', emojiB: '🕯️', category: 'romance' },
  { id: 9, optionA: 'Street food adventure', emojiA: '🍜', optionB: 'Fancy restaurant', emojiB: '🍷', category: 'food' },
  { id: 10, optionA: 'Read books', emojiA: '📚', optionB: 'Watch shows/anime', emojiB: '📺', category: 'entertainment' },
  { id: 11, optionA: 'City life', emojiA: '🏙️', optionB: 'Countryside/quiet', emojiB: '🌿', category: 'lifestyle' },
  { id: 12, optionA: 'Handwritten letters', emojiA: '✉️', optionB: 'Voice messages', emojiB: '🎙️', category: 'romance' },
  { id: 13, optionA: 'Spicy food', emojiA: '🌶️', optionB: 'Mild and flavorful', emojiB: '🍲', category: 'food' },
  { id: 14, optionA: 'Live in the present', emojiA: '⏳', optionB: 'Plan for the future', emojiB: '🔮', category: 'lifestyle' },
  { id: 15, optionA: 'Anime marathon', emojiA: '⛩️', optionB: 'Movie binge night', emojiB: '🎥', category: 'entertainment' },
  { id: 16, optionA: 'Homebody weekend', emojiA: '🏠', optionB: 'Adventure weekend', emojiB: '🎒', category: 'lifestyle' },
  { id: 17, optionA: 'Rainy day indoors', emojiA: '🌧️', optionB: 'Sunny day outside', emojiB: '☀️', category: 'lifestyle' },
  { id: 18, optionA: 'Love notes in unexpected places', emojiA: '💌', optionB: 'Big romantic gestures', emojiB: '💐', category: 'romance' },
  { id: 19, optionA: 'Sushi', emojiA: '🍣', optionB: 'Biryani', emojiB: '🍛', category: 'food' },
  { id: 20, optionA: 'Music while working', emojiA: '🎵', optionB: 'Complete silence', emojiB: '🤫', category: 'lifestyle' },
  { id: 21, optionA: 'Backpacking trip', emojiA: '🎒', optionB: 'Luxury resort stay', emojiB: '🏨', category: 'travel' },
  { id: 22, optionA: 'Same-city someday', emojiA: '🏡', optionB: 'Travel together forever', emojiB: '🌍', category: 'romance' },
  { id: 23, optionA: 'Ice cream', emojiA: '🍦', optionB: 'Cake', emojiB: '🎂', category: 'food' },
  { id: 24, optionA: 'Watch the sunrise', emojiA: '🌄', optionB: 'Watch the sunset', emojiB: '🌇', category: 'romance' },
  { id: 25, optionA: 'Minimalist living', emojiA: '🪴', optionB: 'Cozy maximalist home', emojiB: '🕯️', category: 'lifestyle' },
  { id: 26, optionA: 'Video games together', emojiA: '🎮', optionB: 'Board/card games', emojiB: '🃏', category: 'entertainment' },
  { id: 27, optionA: 'Road trip', emojiA: '🚗', optionB: 'Train journey', emojiB: '🚂', category: 'travel' },
  { id: 28, optionA: 'Cuddle without talking', emojiA: '🤗', optionB: 'Deep conversation until 3am', emojiB: '🌌', category: 'romance' },
  { id: 29, optionA: 'Chocolate desserts', emojiA: '🍫', optionB: 'Fruit-based desserts', emojiB: '🍓', category: 'food' },
  { id: 30, optionA: 'Small intimate gathering', emojiA: '🥂', optionB: 'Just the two of us', emojiB: '💑', category: 'romance' },
  { id: 31, optionA: 'Podcast person', emojiA: '🎧', optionB: 'Audiobook person', emojiB: '📖', category: 'entertainment' },
  { id: 32, optionA: 'Solo travel sometimes', emojiA: '🧳', optionB: 'Always travel together', emojiB: '👫', category: 'travel' },
  { id: 33, optionA: 'Pets at home', emojiA: '🐾', optionB: 'Plant-filled home', emojiB: '🌱', category: 'lifestyle' },
  { id: 34, optionA: 'Night market stroll', emojiA: '🏮', optionB: 'Quiet cafe afternoon', emojiB: '☕', category: 'romance' },
  { id: 35, optionA: 'Thriller / Horror', emojiA: '😱', optionB: 'Romance / Drama', emojiB: '💕', category: 'entertainment' },
  { id: 36, optionA: 'Celebrate big milestones loudly', emojiA: '🎉', optionB: 'Quiet meaningful moments', emojiB: '🕯️', category: 'romance' },
  { id: 37, optionA: 'Dumplings', emojiA: '🥟', optionB: 'Pasta', emojiB: '🍝', category: 'food' },
  { id: 38, optionA: 'Live in a warm climate', emojiA: '🌴', optionB: 'Live where seasons change', emojiB: '🍂', category: 'lifestyle' },
  { id: 39, optionA: 'Documentary rabbit holes', emojiA: '🔍', optionB: 'Reality TV guilty pleasure', emojiB: '📺', category: 'entertainment' },
];
